### ISSUE TITLE
could you share how did you get the api from aquaclean ?

### ISSUE THREAD

**Issue by licheng5625** [thomas-bingel/geberit-aquaclean#1]
I want to intergrate aquaclean to my smart home. But how did you get the api from them ?

thanks a lot

**Comment by riemers** [comment]
Was just browsing, since i have one too. But to answer, there is no API. It is bluetooth. You can sniff that. So you would need a device close to it in order for it to connect and "talk home" was looking for something in python  though.

**Comment by thomas-bingel** [comment]
It is possible to decompile the AquaClean android app and look into the C# code. It is a Xamarin app as far as I remember. But it is not that easy to get it to work properly. Sometimes I had to "reset" the toilet to connect again. Also it seems that only one device can be connected at a time.

**Comment by geraldnolan** [comment]
@thomas-bingel Thanks for posting this! Do you use this with Home Assistant? 

How did you find out the SERVICE_UUID?

`private Guid SERVICE_UUID = Guid.Parse("3334429d-90f3-4c41-a02d-5cb3a03e0000");`

I have a Geberit DuoFresh that I would like to automate the fan. I can connect to the device but get stuck at the read characteristic code. (**Returns Null**)


            //Register read characteristics
            readCharacteristics.Add(BULK_CHAR_BULK_READ_0_UUID_STRING, DataReceived);
            readCharacteristics.Add(BULK_CHAR_BULK_READ_1_UUID_STRING, DataReceived);
            readCharacteristics.Add(BULK_CHAR_BULK_READ_2_UUID_STRING, DataReceived);
            readCharacteristics.Add(BULK_CHAR_BULK_READ_3_UUID_STRING, DataReceived);

            // Load write characteristic
            var service = await bluetoothLeDevice.GetGattServiceForUuidAsync(SERVICE_UUID);
            var characteristicsResult = await service.GetCharacteristicsAsync();
            var characteristics = characteristicsResult.Characteristics;
            writeCharacteristic = characteristics.First((c) => c.Uuid == BULK_CHAR_BULK_WRITE_0_UUID_STRING);

The app that I have in iOS (US app store ) Geberit Control is not the same one as you can get in Europe.

What application do you use to sniff the bluetooth traffic like wireshark?

**Comment by thomas-bingel** [comment]
@geraldnolan I did not use WireShark. You can debug the bluetooth on an Android device and get a dump from the transferred data. Then I used the APK from Geberit and stated fiddeling around with the bluetooth characteristict with .NET. 
All the IDs are hard coded into the APK (It is a combination of Java and .NET code). You can decompile the Java and .NET part. After that it is reading the code and figuring out how it works. 

I wanted to use it with my own little home automation tool, but never finished it. The Problem was that it stopped working after a while couple of connects and could not reconnect. Don't know why. Also it seems, that only one device can be connected to the toilet at once. So the remote would not work when the Raspberry PI was connected.

**Comment by jens62** [comment]
> I want to intergrate aquaclean to my smart home. But how did you get the api from them ?
> 
> thanks a lot

I have successfully integrated it into my smart home. 

Maybe my [python port](https://github.com/jens62/geberit-aquaclean) of this project is worth a look.

**Comment by jens62** [comment]
> Was just browsing, since i have one too. But to answer, there is no API. It is bluetooth. You can sniff that. So you would need a device close to it in order for it to connect and "talk home" was looking for something in python though.

Maybe my [python port](https://github.com/jens62/geberit-aquaclean) of this project is worth a look.

**Comment by jens62** [comment]
> @thomas-bingel Thanks for posting this! Do you use this with Home Assistant?
> 
> How did you find out the SERVICE_UUID?
> 
> `private Guid SERVICE_UUID = Guid.Parse("3334429d-90f3-4c41-a02d-5cb3a03e0000");`
> 
> I have a Geberit DuoFresh that I would like to automate the fan. I can connect to the device but get stuck at the read characteristic code. (**Returns Null**)
> 
> ```
>         //Register read characteristics
>         readCharacteristics.Add(BULK_CHAR_BULK_READ_0_UUID_STRING, DataReceived);
>         readCharacteristics.Add(BULK_CHAR_BULK_READ_1_UUID_STRING, DataReceived);
>         readCharacteristics.Add(BULK_CHAR_BULK_READ_2_UUID_STRING, DataReceived);
>         readCharacteristics.Add(BULK_CHAR_BULK_READ_3_UUID_STRING, DataReceived);
> 
>         // Load write characteristic
>         var service = await bluetoothLeDevice.GetGattServiceForUuidAsync(SERVICE_UUID);
>         var characteristicsResult = await service.GetCharacteristicsAsync();
>         var characteristics = characteristicsResult.Characteristics;
>         writeCharacteristic = characteristics.First((c) => c.Uuid == BULK_CHAR_BULK_WRITE_0_UUID_STRING);
> ```
> 
> The app that I have in iOS (US app store ) Geberit Control is not the same one as you can get in Europe.
> 
> What application do you use to sniff the bluetooth traffic like wireshark?

I am using openHAB (see [openHAB screenshot](https://github.com/jens62/geberit-aquaclean/blob/main/operation_support/Geberit%20AquaClean%20with%20openHAB%20-%20Basic%20UI.png)), but thru the "mqtt-abstraction-layer" it will work with Home Assistant as well.
Maybe my [python port](https://github.com/jens62/geberit-aquaclean) of this project is worth a look.

**Comment by jens62** [comment]
The Home Assistant integration via HACS is now available, too. See 
[Geberit AquaClean — HACS Custom Integration](https://github.com/jens62/geberit-aquaclean/blob/main/docs/hacs-integration.md)
