### ISSUE TITLE
Port to ESPHome instead?

### ISSUE THREAD

**Issue by kopierschnitte** [thomas-bingel/geberit-aquaclean#2]
Hi!

Just found your project and I really appreciate your hard work. As far as I can tell it's the only approach to this kind of device.

Maybe it would be a good idea to try porting it to somekind of lightweight gateway device, like ESPHome, in order to control the toilet within Home-Assistant or even iobroker/FHEM. This could enable the usage of wall switches or even voice assistants to do basic tasks (without the need of a permanent connection).

Unfortunately, I'm not very keen in reading UWP code but maybe you could give some "high level" hints on how the pairing process and reading/write is done.

Thanks!

**Comment by Alex-joomla** [comment]
That would be really  great!

**Comment by thomas-bingel** [comment]
I'm afraid I don't have the time to port this to ESPHome at the moment. It's been a while since I wrote the code, but I encourage you to take a look—it's not too complicated.

**Comment by thomas-bingel** [comment]
I'm afraid I don't have the time to port this to ESPHome at the moment. It's been a while since I wrote the code, but I encourage you to take a look—it's not too complicated.

**Comment by kopierschnitte** [comment]
Thanks for replying. May I ask about the pairing process? Is it even necessary to initiate pairing?
I can't find a reference to this in your code...

**Comment by thomas-bingel** [comment]
The pairing was done manually. Please keep in mind that only one device can be connected at a time, so any other devices, such as the controller or touchpad, will no longer function once paired.

**Comment by jens62** [comment]
> Hi!
> 
> Just found your project and I really appreciate your hard work. As far as I can tell it's the only approach to this kind of device.
> 
> Maybe it would be a good idea to try porting it to somekind of lightweight gateway device, like ESPHome, in order to control the toilet within Home-Assistant or even iobroker/FHEM. This could enable the usage of wall switches or even voice assistants to do basic tasks (without the need of a permanent connection).
> 
> Unfortunately, I'm not very keen in reading UWP code but maybe you could give some "high level" hints on how the pairing process and reading/write is done.
> 
> Thanks!

Maybe my [python port](https://github.com/jens62/geberit-aquaclean) of this project is worth a look.
